version: "3"

services:
  mysqlservice:
    image: mysql:8
    ports:
      - 3307:3307
    container_name: mysql-container
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: ADcool@24
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ADcool@24
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 27017:27017

  eureka-server:
    image: eureka-service
    build: eureka-server/
    container_name: eureka-server
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761
    environment:
      EUREKA_SERVER_PORT: 8761
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
          - 8091:8091
    environment:
      API_GATEWAY_PORT: 8091
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761

  product-webapp:
    build: product-webapp/
    image: product-webapp
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    container_name: product-webapp
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
          - 8099:8099
    environment:
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761





  authentication-service:
    build: authentication-service/
    container_name: authentication-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
          - 8081:8081
    environment:
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761


  admin:
      build: authentication-service/
      container_name: authentication-service
      depends_on:
        - eureka-server
        - api-gateway
      restart: always
      #    networks:
      #      - springcloud-movie-net
      network_mode: "host"
      hostname: localhost
      ports:
        - 8089:8089
      environment:
        EUREKA_SERVER_IP: eureka-server                 #localhost
        EUREKA_SERVER_PORT: 8761


#  booking-app:
#    build: booking-service/
#    container_name: booking-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#    restart: always
#    #    networks:
#    #      - springcloud-movie-net
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8079:8079
#    environment:
#      EUREKA_SERVER_IP: eureka-server                 #localhost
#      EUREKA_SERVER_PORT: 8761


  customer-service:
    build: customer-service/
    container_name: customer-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 8090:8090
    environment:
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761



  hotel:
    build: hotel-service/
    container_name: hotel-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 8083:8083
    environment:
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761


  notificationservice:
    build: notification-service/
    container_name: notification-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9095:9095
    environment:
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761

  payment-app:
    build: payment-service/
    container_name: payment-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9097:9097
    environment:
      EUREKA_SERVER_IP: eureka-server                 #localhost
      EUREKA_SERVER_PORT: 8761

#  Review:
#    build: review-service/
#    container_name: review-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#    restart: always
#    #    networks:
#    #      - springcloud-movie-net
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8085:8085
#    environment:
#      EUREKA_SERVER_IP: eureka-server                 #localhost
#      EUREKA_SERVER_PORT: 8761


#networks:
#  springcloud-movie-net:
#    driver: bridge